<?php
namespace Database\Seeders;
use App\Models\GalleryItem; use App\Models\Review; use App\Models\Reel; use App\Models\Service; use App\Models\SiteSetting; use App\Models\User; use App\Models\WorkingHour; use Illuminate\Database\Seeder; use Illuminate\Support\Facades\Hash;
class DatabaseSeeder extends Seeder { public function run():void{
 User::updateOrCreate(['email'=>'admin@lolita.local'],['name'=>'Lolita Admin','password'=>Hash::make('Lolita123!'),'is_admin'=>true]);
 $services=[
 ['name_ar'=>'مانيكير','name_en'=>'Manicure','description_ar'=>'عناية متكاملة بالأظافر والجلد المحيط بها.','price'=>60000,'duration_minutes'=>45,'image'=>'/images/lolita/white-ombre.jpg','sort_order'=>1],
 ['name_ar'=>'جيل بوليش','name_en'=>'Gel Polish','description_ar'=>'لون لامع وثبات طويل مع تشطيب احترافي.','price'=>80000,'duration_minutes'=>60,'image'=>'/images/lolita/pink-stiletto.jpg','sort_order'=>2],
 ['name_ar'=>'تركيب أظافر','name_en'=>'Nail Extensions','description_ar'=>'تطويل وتشكيل الأظافر حسب الستايل المناسب لك.','price'=>120000,'duration_minutes'=>90,'image'=>'/images/lolita/black-tip.jpg','sort_order'=>3],
 ['name_ar'=>'نيل آرت','name_en'=>'Nail Art','description_ar'=>'تصاميم مخصصة من البسيط إلى التفاصيل المميزة.','price'=>90000,'duration_minutes'=>75,'image'=>'/images/lolita/floral-3d.jpg','sort_order'=>4],
 ['name_ar'=>'رموش','name_en'=>'Lashes','description_ar'=>'جلسة رموش بإطلالة ناعمة أو كثيفة حسب الرغبة.','price'=>100000,'duration_minutes'=>90,'image'=>'/images/lolita/extension.jpeg','sort_order'=>5],
 ]; foreach($services as $s) Service::updateOrCreate(['name_en'=>$s['name_en']],$s+['is_active'=>true]);
 for($d=0;$d<7;$d++) WorkingHour::updateOrCreate(['day_of_week'=>$d],['opens_at'=>'10:00','closes_at'=>'20:00','is_closed'=>false]);
 $gallery=[
 ['/images/lolita/white-ombre.jpg','Soft White Ombré','french'],['/images/lolita/pink-stiletto.jpg','Pink Stiletto','gel'],['/images/lolita/floral-3d.jpg','3D Floral Art','art'],['/images/lolita/black-tip.jpg','Graphic French Tips','french'],['/images/lolita/french-flower.jpg','French Floral','french'],['/images/lolita/red-lines.jpg','Burgundy Lines','art'],['/images/lolita/green-cherry.jpg','Cherry Green','art'],['/images/lolita/extension.jpeg','lash extension','lash extension'],['/images/lolita/leopard.jpg','Leopard Details','art'],['/images/lolita/cherry-art.jpg','Cherry Nail Art','gel'],
 ]; foreach($gallery as $i=>$g) GalleryItem::updateOrCreate(['image'=>$g[0]],['title'=>$g[1],'category'=>$g[2],'is_featured'=>$i<6,'sort_order'=>$i+1]);
 $reviews=[['client_name'=>'Rana K.','body'=>'شغل مرتب جداً والنتيجة ناعمة وحلوة.','rating'=>5,'sort_order'=>1],['client_name'=>'Sara M.','body'=>'بحب الاهتمام بالتفاصيل والنظافة، تجربة كتير مريحة.','rating'=>5,'sort_order'=>2],['client_name'=>'Lina A.','body'=>'جو لطيف وشغل جميل، أكيد برجع مرة تانية.','rating'=>5,'sort_order'=>3]]; foreach($reviews as $r) Review::updateOrCreate(['client_name'=>$r['client_name']],$r+['is_published'=>true]);
 $reels=[['video'=>'/videos/lolita-before-after-1.mp4','title'=>'Before / After 1','sort_order'=>1],['video'=>'/videos/lolita-before-after-2.mp4','title'=>'Before / After 2','sort_order'=>2],['video'=>'/videos/lolita-before-after-3.mp4','title'=>'Before / After 3','sort_order'=>3]]; foreach($reels as $r) Reel::updateOrCreate(['video'=>$r['video']],$r+['label'=>'Before → After','is_published'=>true]);
 $settings=['brand_name'=>'Lolita Nails','hero_eyebrow'=>'LOLITA NAILS • LASHES • BEAUTY','hero_title'=>'جمالك يبدأ من التفاصيل','hero_subtitle'=>'تجربة أنثوية راقية، عناية دقيقة، ونتيجة مصممة لتشبهك.','location'=>'اللاذقية، سوريا','phone'=>'0936 812 019','whatsapp'=>'963936812019','instagram_url'=>'https://instagram.com/lolitanails22','instagram_handle'=>'@lolitanails22','followers_label'=>'55K+ followers','booking_policy'=>"يُفضّل الوصول قبل الموعد بـ 5–10 دقائق.\nعند التأخير قد يتم تقليل وقت الخدمة أو إعادة جدولة الموعد.\nالإلغاء أو التعديل يُفضّل أن يكون قبل الموعد بوقت كافٍ.\nأي عربون أو شروط دفع يتم تأكيدها مباشرة عبر WhatsApp إن كانت مطبقة.",'seo_title'=>'Lolita Nails | Nails, Lashes & Beauty','seo_description'=>'Lolita Nails — أظافر، نيل آرت، جيل وتركيب مع حجز موعد أونلاين.','show_gallery'=>'1','show_reels'=>'1','show_reviews'=>'1','show_before_after'=>'0']; foreach($settings as $k=>$v) SiteSetting::put($k,$v);
 }}
